### ISSUE TITLE
FAlcon

### ISSUE THREAD

**Issue by arita37** [facebookresearch/Pearl#16]
Hi,

Tflow Agent implementa Falcon exploration….
Any way to get Falcon in Pearl ?

thanks !

**Comment by rodrigodesalvobraz** [comment]
> Hi,
> 
> Tflow Agent implementa Falcon exploration…. Any way to get Falcon in Pearl ?

Hi. Thank you for your interest. Looking at the Falcon paper, it seems very similar or perhaps identical to the `SquareCB ` exploration we have in Pearl. Can you take a look?

Hopefully `SquareCB ` is already sufficient. But in any case, because Pearl's agent design is modular, it is possible (even for end users such as yourself) to implement new exploration methods relatively easily.
