### ISSUE TITLE
Frozen lake

### ISSUE THREAD

**Issue by mehrdad78** [facebookresearch/Pearl#59]
hi!
i want to solve **_Frozen Lake_** problem with **Pearl**.But how can i do that?i do not know how to use Pearl for solving problems.You said Pearl can be used for real-world problems but you did not provide any example for that.
Please help me!

**Comment by xuruiyang** [comment]
Should this already in our gymnasium benchmark? No?

**Comment by yiwan-rl** [comment]
Hi,

We are sorry that this created confusion to you. Currently we have two tutorials. One is about a [DQN-based news recommender system](https://github.com/facebookresearch/Pearl/tree/main/pearl/tutorials/single_item_recommender_system_example/demo.ipynb) while the other one is a [contextual bandit tutorial](https://github.com/facebookresearch/Pearl/tree/main/pearl/tutorials/contextual_bandits/contextual_bandits_tutorial.ipynb).

In terms of the FrozenLake environment, I think the quick start code shown in the README file is pretty close to a solution. 

One thing important to note here is that the you would like to convert each observation, which is an index of the current state, to some representation vector (like a "one-hot vector") for that state. This is because in our design, all states are assumed to be representation vectors instead of indices.

Then you would obtain some code like this, which works in this problem.
```from pearl.pearl_agent import PearlAgent
from pearl.action_representation_modules.one_hot_action_representation_module import (
    OneHotActionTensorRepresentationModule,
)
from pearl.policy_learners.sequential_decision_making.deep_q_learning import (
    DeepQLearning,
)
from pearl.replay_buffers.sequential_decision_making.fifo_off_policy_replay_buffer import (
    FIFOOffPolicyReplayBuffer,
)
from pearl.utils.instantiations.environments.gym_environment import GymEnvironment
import numpy as np
env = GymEnvironment("FrozenLake-v1", is_slippery=False)

num_actions = env.action_space.n
agent = PearlAgent(
    policy_learner=DeepQLearning(
        state_dim=env.observation_space.n,
        action_space=env.action_space,
        hidden_dims=[64],
        training_rounds=20,
        action_representation_module=OneHotActionTensorRepresentationModule(
            max_number_actions=num_actions
        ),
    ),
    replay_buffer=FIFOOffPolicyReplayBuffer(10_000),
)
for i in range(1000):
    observation, action_space = env.reset()
    # convert observation, which is an index, to an one-hot vector
    tmp = np.zeros(env.observation_space.n, dtype=float)
    tmp[observation] = 1
    observation = tmp.astype(np.float32)
    agent.reset(observation, action_space)
    done = False
    rtn = 0
    while not done:
        action = agent.act(exploit=False)
        action_result = env.step(action)
        # convert observation, which is an index, to an one-hot vector
        tmp = np.zeros(env.observation_space.n, dtype=float)
        tmp[action_result.observation] = 1
        action_result.observation = tmp.astype(np.float32)
        agent.observe(action_result)
        agent.learn()
        done = action_result.done
        rtn += action_result.reward
        if done:
            print(f"Episode: {i}, Return: {rtn} ")

**Comment by mehrdad78** [comment]
So nice!thank you .
If i have any other question about solving problems like that,should comment here or open new issue?

**Comment by yiwan-rl** [comment]
You are welcome. We are glad that you play with the code and provide feedback.

If the new questions are not related to this issue, I suggest starting a new issue.

**Comment by rodrigodesalvobraz** [comment]
Please note we have revised the code example to avoid having to mess with numpy and numpy dtypes.

We also introduced a one_hot_vector function to make that operation more evident, and selected a very small environment (size 3) to make execution fast to check.

**Comment by rodrigodesalvobraz** [comment]
Please note we have added a [FrozenLake Jupyter notebook tutorial](https://github.com/facebookresearch/Pearl/blob/main/tutorials/frozen_lake/frozen_lake.ipynb) that's an even simpler version (using the `online_learning` function which automates the learning loop for you).
