### ISSUE TITLE
Use pearl with custom pytorch model

### ISSUE THREAD

**Issue by BoccheseGiacomo** [facebookresearch/Pearl#60]
Used to use pytorch + gym for RL.
Is there a way to make a custom neural net in pytorch and insert it into the pearl agent without using the pre-made settings for neural nets?

**Comment by rodrigodesalvobraz** [comment]
It is possible to directly provide a network instance to be used by policy learners implementing Temporal Difference (TD learning) methods:

- all direct and indirect subclasses of [DeepTDLearning](https://pearlagent.github.io/policy_learners/sequential_decision_making/deep_td_learning.html#pearl.policy_learners.sequential_decision_making.deep_td_learning.DeepTDLearning) ([DeepQLearning](https://pearlagent.github.io/policy_learners/sequential_decision_making/deep_q_learning.html#pearl.policy_learners.sequential_decision_making.deep_q_learning.DeepQLearning), [DeepSARSA](https://pearlagent.github.io/policy_learners/sequential_decision_making/deep_sarsa.html#pearl.policy_learners.sequential_decision_making.deep_sarsa.DeepSARSA), [DoubleDQN](https://pearlagent.github.io/policy_learners/sequential_decision_making/double_dqn.html#pearl.policy_learners.sequential_decision_making.double_dqn.DoubleDQN), among others), since `DeepTDLearning` accepts an initialization parameter `network_instance`, which must be an instance of [QValueNetwork](https://pearlagent.github.io/neural_networks/sequential_decision_making/q_value_network.html#pearl.neural_networks.sequential_decision_making.q_value_network.QValueNetwork).
While `network_instance` does not explicitly appear in the documentation of the `__init__` methods of the subclasses, the parameter can be passed to them as a keyword argument (`kwargs`) and will be used by their super class.
Here's [an example of `network_instance` being used for `DeepQLearning`](https://github.com/facebookresearch/Pearl/blob/791a5b3837eff557e6b85b409e26eb91ee04ff83/test/integration/test_integration.py#L245).

- All direct and indirect classes of [QuantileRegressionDeepTDLearning](https://pearlagent.github.io/policy_learners/sequential_decision_making/quantile_regression_deep_td_learning.html#pearl.policy_learners.sequential_decision_making.quantile_regression_deep_td_learning.QuantileRegressionDeepTDLearning) (currently, this is only [QuantileRegressionDeepQLearning](https://pearlagent.github.io/policy_learners/sequential_decision_making/quantile_regression_deep_q_learning.html#pearl.policy_learners.sequential_decision_making.quantile_regression_deep_q_learning.QuantileRegressionDeepQLearning)).
This class also accepts a `network_instance` parameter, but this time it must be an instance of [QuantileQValueNetwork](https://pearlagent.github.io/neural_networks/common/value_networks.html#pearl.neural_networks.common.value_networks.QuantileQValueNetwork).
There is currently no example of this in the code base because the test for `QuantileRegressionDeepQLearning` uses the default network type, but its use is analogous to the `DeepQLearning` example linked above.

Moreover, while it is not possible to directly provide network instances to the subclasses of [ActorCriticBase](https://pearlagent.github.io/policy_learners/sequential_decision_making/actor_critic_base.html#pearl.policy_learners.sequential_decision_making.actor_critic_base.ActorCriticBase), it is possible to request the use of custom user network *classes*. These policy learners accept `actor_network_type` and `critic_network_type` parameters which allows the user to specify the _classes_ to be used for those networks. So the user can define their custom network classes and pass those to be used. They must be subclasses of [ActorNetwork](https://pearlagent.github.io/neural_networks/sequential_decision_making/actor_networks.html#pearl.neural_networks.sequential_decision_making.actor_networks.ActorNetwork) and [QValueNetwork](https://pearlagent.github.io/neural_networks/sequential_decision_making/q_value_network.html#pearl.neural_networks.sequential_decision_making.q_value_network.QValueNetwork) classes respectively.

**Comment by BoccheseGiacomo** [comment]
@rodrigodesalvobraz 

Thank you. it's clear.

Another small question: can i add custom properties to my agent? for example if i want my agent to have some properties that are properties of the agent, not of the environment, for example "money". Imagine i'm running a simulation of a market economy environment, and i want each agent to possess some float attributes like money, health, hunger etc. 

Can i do this with pearl?
In gym i would simply insert these properties in my "agent" class

**Comment by rodrigodesalvobraz** [comment]
Adding a property to an object is always possible in Python in general, regardless of the libraries one might be using. If you have a object instance `agent`, writing `agent.money = 10` will work and be accessible from then on.

However, I suspect this might not be what you would really want. If you want the RL algorithm to take these properties into account when making decisions for the agent (for example, the agent will be more likely to spend money if it has a lot of it, but will try to save when it does not), then what you really want is to include that information in the observations being received by the agent (if you happen to be using an environment, then the environment is a good candidate to keep this information and include it in the observations it provides). This is because RL algorithms will make decisions based on the information contained in observations (states).

It might be a bit odd to think that an agent's property is being included in the observations coming from the outside world since we tend to think of it as an internal property, but one way to think about it is that the agent is _observing_ things, including how much money is in its pocket!

Because Pearl currently represents observations as tensors, you might want to use a representation such that the agent's properties of interest are concatenated with the rest of the observation into a single tensor.

To keep the property up-to-date (for example, to decrease the agent's money once a decision is made to spend some), the code receiving the action from the agent (in learning situations this will typically be the `step` method of the environment) must modify the property's value according to the action taken.

I hope this helps.

**Comment by rodrigodesalvobraz** [comment]
The solution you mention (keeping the properties inside the agent instance and concatenating them to the external observation) might actually work, too.

It seems to be a little less conventional. Usually in an RL problem one talks about a single type of observation, but here you have two types, the external one and the internal one obtained from concatenating agent's properties to the first one. Software libraries often makes assumptions based on conventions, so going a less conventional route may turn out tricky, but as far as I can tell right now your approach could work too.

**Comment by BoccheseGiacomo** [comment]
thank you again
